import mongoose from "mongoose";
import { Alert } from "@/models/Alert";
import { Stock } from "@/models/Stock";
import { Product } from "@/models/Product";
import { Warehouse } from "@/models/Warehouse";
import { User } from "@/models/User";
import { sendEmail } from "@/lib/email";

// ── Email template ─────────────────────────────────────────────────────────────

function buildAlertEmail(title: string, message: string, recommendation: string) {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "";
  return `
    <div style="font-family:-apple-system,sans-serif;max-width:600px;margin:0 auto;">
      <div style="background:#111827;padding:24px;border-radius:12px 12px 0 0;">
        <p style="color:#9ca3af;margin:0 0 6px;font-size:12px;text-transform:uppercase;letter-spacing:1px;">Inventory Tracker</p>
        <h1 style="color:#fff;margin:0;font-size:20px;">⚠️ Critical Alert</h1>
      </div>
      <div style="border:1px solid #e5e7eb;border-top:none;padding:28px;border-radius:0 0 12px 12px;background:#fff;">
        <h2 style="color:#dc2626;margin:0 0 12px;font-size:18px;">${title}</h2>
        <p style="color:#374151;margin:0 0 20px;line-height:1.6;">${message}</p>
        <div style="background:#fffbeb;border-left:4px solid #f59e0b;padding:14px 16px;border-radius:0 8px 8px 0;margin-bottom:24px;">
          <p style="color:#92400e;margin:0;font-size:14px;"><strong>Recommended action:</strong> ${recommendation}</p>
        </div>
        <a href="${appUrl}/dashboard/alerts"
           style="display:inline-block;background:#dc2626;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;font-size:14px;">
          View in Dashboard →
        </a>
        <p style="color:#9ca3af;font-size:12px;margin:20px 0 0;">This alert was automatically generated by your inventory system.</p>
      </div>
    </div>
  `;
}

// ── Core upsert ────────────────────────────────────────────────────────────────

async function upsertAlert(params: {
  companyId: mongoose.Types.ObjectId;
  type: string;
  severity: "critical" | "warning" | "info";
  title: string;
  message: string;
  recommendation: string;
  metadata: Record<string, unknown>;
  warehouseId: mongoose.Types.ObjectId;
  stockId?: mongoose.Types.ObjectId;
  productId?: mongoose.Types.ObjectId;
  adminEmail?: string;
}) {
  const { companyId, type, severity, title, message, recommendation, metadata, warehouseId, stockId, productId, adminEmail } = params;

  // Skip if an active alert already exists for this exact target + type
  const dedupQuery: Record<string, unknown> = {
    companyId,
    warehouseId,
    type,
    status: { $in: ["open", "acknowledged"] },
  };
  if (stockId) dedupQuery.stockId = stockId;
  if (productId) dedupQuery.productId = productId;

  const existing = await Alert.findOne(dedupQuery);
  if (existing) return;

  await Alert.create({ companyId, stockId, productId, warehouseId, type, severity, title, message, recommendation, metadata, status: "open" });

  if (severity === "critical" && adminEmail) {
    sendEmail({ to: adminEmail, subject: `Critical Alert: ${title}`, html: buildAlertEmail(title, message, recommendation) })
      .catch((e) => console.error("Alert email failed:", e));
  }
}

async function autoResolve(alertId: mongoose.Types.ObjectId, note: string) {
  await Alert.updateOne({ _id: alertId }, { status: "resolved", resolvedAt: new Date(), resolvedNotes: note });
}

// ── Cron: all aging / dead / expiry / warehouse capacity ───────────────────────

export async function generateCronAlerts(companyId: mongoose.Types.ObjectId) {
  const admin = await User.findOne({ companyId, role: "super_admin", isActive: true }).select("email").lean();
  const adminEmail = admin?.email as string | undefined;

  const now = new Date();
  const in7days  = new Date(now.getTime() +  7 * 24 * 60 * 60 * 1000);
  const in30days = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

  // ── Dead stock ───────────────────────────────────────────────────────────────
  const deadBatches: any[] = await Stock.find({ companyId, ageInDays: { $gte: 180 }, quantityAvailable: { $gt: 0 } })
    .populate("productId", "name sku unitPrice")
    .populate("warehouseId", "name")
    .lean();

  for (const batch of deadBatches) {
    const p = batch.productId;
    const w = batch.warehouseId;
    await upsertAlert({
      companyId, type: "dead_inventory", severity: "critical",
      stockId: batch._id as mongoose.Types.ObjectId,
      productId: p._id, warehouseId: w._id,
      title: `Dead Stock: ${p.name}`,
      message: `${batch.quantityAvailable} units of ${p.name} (${p.sku}) in ${w.name} have been sitting for ${batch.ageInDays} days with no movement.`,
      recommendation: `Consider discounting, transferring, or writing off this stock to free up warehouse space.`,
      metadata: { ageInDays: batch.ageInDays, quantity: batch.quantityAvailable, value: batch.quantityAvailable * (p.unitPrice ?? 0) },
      adminEmail,
    });
  }

  // ── Aging stock (120–179 days) ───────────────────────────────────────────────
  const agingBatches: any[] = await Stock.find({ companyId, ageInDays: { $gte: 120, $lt: 180 }, quantityAvailable: { $gt: 0 } })
    .populate("productId", "name sku")
    .populate("warehouseId", "name")
    .lean();

  for (const batch of agingBatches) {
    const p = batch.productId;
    const w = batch.warehouseId;
    await upsertAlert({
      companyId, type: "aging", severity: "warning",
      stockId: batch._id as mongoose.Types.ObjectId,
      productId: p._id, warehouseId: w._id,
      title: `Aging Stock: ${p.name}`,
      message: `${batch.quantityAvailable} units of ${p.name} (${p.sku}) in ${w.name} have been in stock for ${batch.ageInDays} days.`,
      recommendation: `Monitor this batch closely. If there is no movement in the next ${180 - batch.ageInDays} days it will be classified as dead stock.`,
      metadata: { ageInDays: batch.ageInDays, quantity: batch.quantityAvailable },
    });
  }

  // ── Expiry warning ───────────────────────────────────────────────────────────
  const expiringBatches: any[] = await Stock.find({
    companyId,
    expiryDate: { $ne: null, $gt: now, $lte: in30days },
    quantityAvailable: { $gt: 0 },
  })
    .populate("productId", "name sku unitPrice")
    .populate("warehouseId", "name")
    .lean();

  for (const batch of expiringBatches) {
    const p = batch.productId;
    const w = batch.warehouseId;
    const daysLeft = Math.ceil((new Date(batch.expiryDate!).getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
    const isCritical = daysLeft <= 7;

    await upsertAlert({
      companyId, type: "expiry_warning", severity: isCritical ? "critical" : "warning",
      stockId: batch._id as mongoose.Types.ObjectId,
      productId: p._id, warehouseId: w._id,
      title: `${isCritical ? "Expiring Soon" : "Expiry Warning"}: ${p.name}`,
      message: `${batch.quantityAvailable} units of ${p.name} (${p.sku}) in ${w.name} expire in ${daysLeft} day${daysLeft === 1 ? "" : "s"}.`,
      recommendation: isCritical
        ? `Immediate action required — prioritise dispatch or arrange disposal before the expiry date.`
        : `Plan to dispatch this stock before expiry. Consider promotional pricing to clear it faster.`,
      metadata: { expiryDate: batch.expiryDate, quantity: batch.quantityAvailable, value: batch.quantityAvailable * (p.unitPrice ?? 0) },
      adminEmail: isCritical ? adminEmail : undefined,
    });
  }

  // ── Warehouse capacity ───────────────────────────────────────────────────────
  const warehouses = await Warehouse.find({ companyId, isActive: true }).select("name capacity").lean();

  for (const wh of warehouses) {
    const [agg] = await Stock.aggregate([
      { $match: { companyId, warehouseId: wh._id } },
      { $group: { _id: null, total: { $sum: "$quantityAvailable" } } },
    ]);
    const total = agg?.total ?? 0;
    const capacity = wh.capacity ?? 1000;
    const pct = total / capacity;

    if (pct >= 0.9) {
      const isCritical = pct >= 1.0;
      await upsertAlert({
        companyId, type: "warehouse_full", severity: isCritical ? "critical" : "warning",
        warehouseId: wh._id as mongoose.Types.ObjectId,
        title: `${isCritical ? "Warehouse Over Capacity" : "Warehouse Nearly Full"}: ${wh.name}`,
        message: `${wh.name} is at ${Math.round(pct * 100)}% capacity (${total} of ${capacity} units).`,
        recommendation: isCritical
          ? `Stop new stock entries immediately. Arrange transfers or expedite dispatches to free space.`
          : `Plan incoming stock carefully — the warehouse will reach full capacity soon.`,
        metadata: { quantity: total, capacityPercent: Math.round(pct * 100) },
        adminEmail: isCritical ? adminEmail : undefined,
      });
    }
  }

  // ── Auto-resolve: low_stock alerts that are no longer low ────────────────────
  const staleLowStock: any[] = await Alert.find({ companyId, type: "low_stock", status: { $in: ["open", "acknowledged"] } })
    .populate("productId", "reorderLevel")
    .lean();

  for (const alert of staleLowStock) {
    const p = alert.productId;
    if (!p) continue;
    const [agg] = await Stock.aggregate([
      { $match: { companyId, productId: p._id, warehouseId: alert.warehouseId } },
      { $group: { _id: null, total: { $sum: "$quantityAvailable" } } },
    ]);
    if ((agg?.total ?? 0) >= p.reorderLevel) {
      await autoResolve(alert._id as mongoose.Types.ObjectId, "Auto-resolved: stock replenished");
    }
  }

  // ── Auto-resolve: warehouse_full alerts that are no longer full ──────────────
  const staleCapacity: any[] = await Alert.find({ companyId, type: "warehouse_full", status: { $in: ["open", "acknowledged"] } }).lean();

  for (const alert of staleCapacity) {
    const wh = await Warehouse.findById(alert.warehouseId).select("capacity").lean();
    if (!wh) continue;
    const [agg] = await Stock.aggregate([
      { $match: { companyId, warehouseId: alert.warehouseId } },
      { $group: { _id: null, total: { $sum: "$quantityAvailable" } } },
    ]);
    const pct = (agg?.total ?? 0) / (wh.capacity ?? 1000);
    if (pct < 0.9) {
      await autoResolve(alert._id as mongoose.Types.ObjectId, "Auto-resolved: capacity freed up");
    }
  }
}

// ── Mutation-triggered: low stock check (call after stock exit) ────────────────

export async function checkLowStockAlert(
  companyId: mongoose.Types.ObjectId,
  productId: mongoose.Types.ObjectId,
  warehouseId: mongoose.Types.ObjectId
) {
  const [productDoc, [agg]] = await Promise.all([
    Product.findById(productId).select("name sku reorderLevel unitPrice").lean(),
    Stock.aggregate([
      { $match: { companyId, productId, warehouseId } },
      { $group: { _id: null, total: { $sum: "$quantityAvailable" } } },
    ]),
  ]);

  if (!productDoc) return;
  const total = agg?.total ?? 0;

  if (total < (productDoc as any).reorderLevel) {
    const [admin, warehouse] = await Promise.all([
      User.findOne({ companyId, role: "super_admin", isActive: true }).select("email").lean(),
      Warehouse.findById(warehouseId).select("name").lean(),
    ]);
    const p = productDoc as any;
    const whName = (warehouse as any)?.name ?? "warehouse";

    await upsertAlert({
      companyId, type: "low_stock", severity: "warning",
      productId, warehouseId,
      title: `Low Stock: ${p.name}`,
      message: `Only ${total} unit${total !== 1 ? "s" : ""} of ${p.name} (${p.sku}) remain in ${whName}, below the reorder level of ${p.reorderLevel}.`,
      recommendation: `Raise a purchase order to replenish ${p.name} in ${whName}.`,
      metadata: { quantity: total, value: total * (p.unitPrice ?? 0) },
      adminEmail: undefined, // low_stock is warning only — no email
    });
  } else {
    // Stock is back above reorder level — resolve any open alert
    await Alert.updateMany(
      { companyId, productId, warehouseId, type: "low_stock", status: { $in: ["open", "acknowledged"] } },
      { status: "resolved", resolvedAt: new Date(), resolvedNotes: "Auto-resolved: stock replenished" }
    );
  }
}

// ── Mutation-triggered: warehouse capacity check (call after stock entry) ──────

export async function checkWarehouseCapacityAlert(
  companyId: mongoose.Types.ObjectId,
  warehouseId: mongoose.Types.ObjectId
) {
  const [wh, [agg]] = await Promise.all([
    Warehouse.findById(warehouseId).select("name capacity").lean(),
    Stock.aggregate([
      { $match: { companyId, warehouseId } },
      { $group: { _id: null, total: { $sum: "$quantityAvailable" } } },
    ]),
  ]);

  if (!wh) return;
  const total = agg?.total ?? 0;
  const capacity = (wh as any).capacity ?? 1000;
  const pct = total / capacity;

  if (pct >= 0.9) {
    const isCritical = pct >= 1.0;
    const admin = isCritical
      ? await User.findOne({ companyId, role: "super_admin", isActive: true }).select("email").lean()
      : null;
    const whDoc = wh as any;

    await upsertAlert({
      companyId, type: "warehouse_full", severity: isCritical ? "critical" : "warning",
      warehouseId,
      title: `${isCritical ? "Warehouse Over Capacity" : "Warehouse Nearly Full"}: ${whDoc.name}`,
      message: `${whDoc.name} is at ${Math.round(pct * 100)}% capacity (${total} of ${capacity} units).`,
      recommendation: isCritical
        ? `Stop new stock entries immediately. Arrange transfers or expedite dispatches to free space.`
        : `Plan incoming stock carefully — the warehouse will reach full capacity soon.`,
      metadata: { quantity: total, capacityPercent: Math.round(pct * 100) },
      adminEmail: isCritical ? (admin as any)?.email : undefined,
    });
  } else {
    await Alert.updateMany(
      { companyId, warehouseId, type: "warehouse_full", status: { $in: ["open", "acknowledged"] } },
      { status: "resolved", resolvedAt: new Date(), resolvedNotes: "Auto-resolved: capacity freed up" }
    );
  }
}
